AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy an ECR Metrics tracker

Resources:

  # Lambda function that captures the metrics into CloudWatch
  EcrMetrics:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Policies:
        # Give the function access to what it needs
        - Statement:
          - Sid: AllowEcrTrackingToCloudWatch
            Effect: Allow
            Action:
              - ecr:DescribeRepositories
              - ecr:DescribeImages
              - cloudwatch:PutMetricData
            Resource: '*'
      Events:
        CronEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(30 minutes)
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile