AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent stack that deploys a sample workflow for signing and verifying
             the signatures on container images at runtime.

Resources:

  # The registry and AWS Signer setup
  RegistryStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: registry.yml

Outputs:
  SignedRepositoryUri:
    Description: The URI to use for pushing container images to the private registry
    Value: !GetAtt RegistryStack.Outputs.SignedRepositoryUri
  LambdaRepositoryUri:
    Description: The URI to use for pushing container images for lambda
    Value: !GetAtt RegistryStack.Outputs.LambdaRepositoryUri
  SigningProfileArn:
    Description: An ARN referencing the signing profile
    Value: !GetAtt RegistryStack.Outputs.SigningProfileArn