name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - id: label
        uses: actions/labeler@v4
        with:
          sync-labels: true
          repo-token: ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.FORK }}
