AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ECR Metrics
Resources:
  EcrMetrics:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Policies:
        # Give the function access to what it needs
        - Statement:
          - Sid: AllowEcrTrackingToCloudWatch
            Effect: Allow
            Action:
              - ecr:DescribeRepositories
              - ecr:DescribeImages
              - cloudwatch:PutMetricData
            Resource: '*'
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile